#cp ./output_files/*.sof .
rm -rf db
rm -rf incremental_db
rm -rf output_files
rm -rf hps_isw_handoff
#rm -rf soc_hps
#rm -rf soc_hps/simulation
#rm -rf soc_hps/synthesis
#rm -rf soc_hps/*.rpt
#rm -rf soc_hps/*.xml
#rm -rf soc_hps/*.html
#rm -rf soc_hps/*.bsf
rm -rf software
#rm -rf software/spl_bsp/generated
#rm -f  software/spl_bsp/*.ds
#rm -f  software/spl_bsp/*.bsp
#rm -f  software/spl_bsp/*.bin
#rm -rf software/spl_bsp/uboot-socfpga
rm -f *.rpt
rm -f *.tcl~
rm -f *.csv
rm -f *.qws
rm -f *.rbf
rm -f *.sopcinfo
rm -f c5_pin*.txt
rm -rf .qsys_edit
rm -f hps_sdram_p0_all_pins.txt
rm -f *.bak
rm -f rtl/*.bak
